In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
pd.__version__

'3.0.6'

In [6]:
len(df)

10000

In [7]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5

In [14]:
df_asia = df[df['origin'] == 'Asia']
df_asia['fuel_efficiency_mpg'].max()

np.float64(41.2)

## Q6

In [10]:
median_1 = df['horsepower'].median()

mode = df['horsepower'].mode().iloc[0]

print(f"mdeian 1 =  {median_1} \nmode =  {mode}\n")

filled_hp = df.copy()
filled_hp['horsepower'] = filled_hp['horsepower'].fillna(mode)
median_2 = filled_hp['horsepower'].median()

mdeian 1 =  254.0
mode =  252.0

In [11]:
filled_hp.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [12]:
print(f"median 2 = {median_2}")

median 2 = 252.0

## Q7

In [39]:
df_2cols = df_asia[['vehicle_weight', 'model_year']].head(7)
df_2cols.head()

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007

In [40]:
X = df_2cols.to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [41]:
TX =X.T
print(TX)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

In [46]:
XTX = TX.dot(X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [43]:
import numpy as np

In [47]:
inv_XTX = np.linalg.inv(XTX)
print(inv_XTX)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [48]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [49]:
w = inv_XTX.dot(TX).dot(y)

In [50]:
w.sum()

np.float64(0.36919696904925486)